image: docker:1.12
services:
  - docker:1.12-dind

stages:
  - test
  - release
  - deploy

variables:
  IMAGE_NAME: nib0r/docker-flow-proxy-letsencrypt
  GITLAB_IMAGE_NAME: docker.nibor.me/robin/docker-flow-proxy-letsencrypt

functional_tests_manual:
  stage: test
  variables:
    DOCKER_CERT_PATH: ${_DOCKER_CERT_PATH}
    DOCKER_HOST: ${_DOCKER_HOST}
    DOCKER_MACHINE_NAME: ${_DOCKER_MACHINE_NAME}
    DOCKER_TLS_VERIFY: ${_DOCKER_TLS_VERIFY}
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest tests.py
  tags:
    - shell
    - ks2.nibor.me
  when: manual
  only:
    - /^feature-.*$/

functional_tests:
  stage: test
  variables:
    DOCKER_CERT_PATH: ${_DOCKER_CERT_PATH}
    DOCKER_HOST: ${_DOCKER_HOST}
    DOCKER_MACHINE_NAME: ${_DOCKER_MACHINE_NAME}
    DOCKER_TLS_VERIFY: ${_DOCKER_TLS_VERIFY}
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest tests.py
  tags:
    - shell
    - ks2.nibor.me
  only:
    - develop
    - master
    - tags

test:
  stage: test
  script:
    - pip install -r requirements-test.txt --upgrade
    - pytest app/client_dfple_tests.py
    - pytest app/client_certbot_tests.py
  tags:
    - shell
    - ks2.nibor.me
  only:
    - develop
    - /^feature-.*$/
    - /^release-.*$/
    - master
    - tags

release:
  stage: release
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $IMAGE_NAME:latest
  tags:
    - docker
    - ks2.nibor.me
  only:
    - master

release_gitlab:
  stage: release
  script:
    - docker build -t $GITLAB_IMAGE_NAME:${CI_BUILD_REF_NAME} .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN docker.nibor.me
    - docker push $GITLAB_IMAGE_NAME:${CI_BUILD_REF_NAME}
  tags:
    - docker
    - ks2.nibor.me

release_develop:
  stage: release
  script:
    - docker build -t $IMAGE_NAME:${CI_BUILD_REF_NAME} .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push $IMAGE_NAME:${CI_BUILD_REF_NAME}
  tags:
    - docker
    - ks2.nibor.me
  only:
    - develop

release_tags:
  stage: release
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker build -t ${IMAGE_NAME}:${CI_BUILD_TAG} .
    - docker push ${IMAGE_NAME}:$CI_BUILD_TAG
  only:
    - tags
  tags:
    - ks2.nibor.me

release_docs:
  stage: release
  script:
    - docker build -f Dockerfile.docs -t nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_REF_NAME} .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_REF_NAME}
  tags:
    - shell
    - ks2.nibor.me
  only:
    - develop


release_docs_master:
  stage: release
  script:
    - docker build -f Dockerfile.docs -t nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_REF_NAME} .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_REF_NAME}
    - curl -X POST "https://jenkins.dockerflow.com/job/n1b0r/job/docker-flow-proxy-letsencrypt/buildWithParameters?token=n1b0r&tag=${CI_BUILD_REF_NAME}"
  tags:
    - shell
    - ks2.nibor.me
  only:
    - master

docs_tags:
  stage: release
  script:
    - docker build -f Dockerfile.docs -t nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_TAG} .
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker push nib0r/docker-flow-proxy-letsencrypt-docs:${CI_BUILD_TAG}
  tags:
    - shell
    - ks2.nibor.me
  only:
    - tags

docs:
  stage: deploy
  script:
    - docker service rm docker-flow-proxy-letsencrypt-docs || true
    - docker service create --name docker-flow-proxy-letsencrypt-docs --network proxy --label com.df.notify=true --label com.df.distribute=true --label com.df.serviceDomain=dfple-docs.ks2.nibor.me --label com.df.servicePath=/ --label com.df.srcPort=443 --label com.df.port=80 --label com.df.letsencrypt.host=dfple-docs.ks2.nibor.me --label com.df.letsencrypt.email=robinlucbernet@gmail.com nib0r/docker-flow-proxy-letsencrypt-docs:master
  tags:
    - shell
    - ks2.nibor.me
  only:
    - master